// action names

export const SET_PLAYER_INFO = "SET_PLAYER_INFO";
export const BUTTONS_PRESSED = "BUTTONS_PRESSED"
export const CLEAR_BUTTONS_PRESSED = "CLEAR_BUTTONS_PRESSED"
export const CLEAR_WIRES_PRESSED = "CLEAR_WIRES_PRESSED"
